name: Markdown List Generator

on:
  push:  # 在代码推送时触发工作流

jobs:
  generate-markdown-list:
    runs-on: ubuntu-latest
    steps:
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Let's add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Let's add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
